import { DigestResult } from "@git2txt/core"

export const siteConfig = {
  name: "Git2txt",
  slogan: "LLM‑ready code in one click",
  title: "Turn any Git repo into LLM‑ready text.",
  username: "thelastofinusa",
  nickname: "Holiday",
  description:
    "Git2txt converts any GitHub repository into a structured text digest ready to paste into ChatGPT, Claude, or any AI.",
  buildExportHeader: (data: DigestResult) => {
    const repoUrl = `https://github.com/${data.owner}/${data.repo}`
    const date = new Date().toISOString().split("T")[0] // YYYY-MM-DD
    const files = data.files.length
    const tokens = data.estimatedTokens
    return `// ============================================================
// Repository Digest
// Generated by Git2txt - https://git2txt.vercel.app
// ============================================================
// Use this file as context for a Large Language Model.
// It contains the entire repository structure and file contents
// in a single, well-formatted document.
//
// Repository: ${repoUrl}
// Date: ${date}
// Files included: ${files.toLocaleString()}
// Estimated tokens: ~${tokens.toLocaleString()}
// ============================================================
`
  },
}
