import { DigestResult } from "@/types"

export const siteConfig = {
  name: "git2txt",
  title: "Turn any repo into LLM‑ready text",
  description:
    "git2txt converts any GitHub repository into a structured text digest — ready to paste into ChatGPT, Claude, or any AI.",
  buildExportHeader: (data: DigestResult) => {
    const repoUrl = `https://github.com/${data.owner}/${data.repo}`
    const date = new Date().toISOString().split("T")[0] // YYYY-MM-DD
    const files = data.files.length
    const tokens = data.estimatedTokens
    return `// ============================================================
// Repository Digest
// Generated by git2txt — https://git2txt.vercel.app
// ============================================================
// Use this file as context for a Large Language Model.
// It contains the entire repository structure and file contents
// in a single, well‑formatted document.
//
// Repository: ${repoUrl}
// Date: ${date}
// Files included: ${files.toLocaleString()}
// Estimated tokens: ~${tokens.toLocaleString()}
// ============================================================
`
  },
}
